### ISSUE TITLE
Crash when hovering over certain wands

### ISSUE THREAD

**Issue by cauliflower69** [romelo333/notenoughwands#5] opened 2016-01-14 14:04 UTC
Using the latest version for 1.8.9

https://youtu.be/8lvAMw9nXgc

**Comment by McJty** [comment] 2016-01-14 14:12
We will check it out

**Comment by rckymtnrfc** [comment] 2016-01-16 22:12
Here is what I'm seeing on the server side when this happens.

http://pastebin.com/ZQ8ywP3u

**Comment by cauliflower69** [comment] 2016-01-16 22:14
@rckymtnrfc Thanks for the additional information

**Comment by McJty** [comment] 2016-01-17 04:39
We will try to fix this today

**Comment by McJty** [comment] 2016-01-17 16:58
We cannot reproduce this. We tried single player, server, anything. What version of Not Enough Wands are you using?

**Comment by cauliflower69** [comment] 2016-01-17 17:00
1.2.4

**Comment by McJty** [comment] 2016-01-17 17:02
Could you give us the full log? Both server and client?

**Comment by rckymtnrfc** [comment] 2016-01-17 17:45
Client crash-log - http://pastebin.com/RhLD3sUE

Server log - http://pastebin.com/XH3gFQnf

I'm using Forge 1699, JEI 2.18.1.88 and NEW 1.2.4

**Comment by McJty** [comment] 2016-01-17 17:53
Hmm, the client crash is actually in JEI

**Comment by rckymtnrfc** [comment] 2016-01-17 18:39
I updated to 2.19.0.93 and now the client doesn't crash, I just disconnect from the client.

**Comment by rckymtnrfc** [comment] 2016-01-17 19:19
from the server I mean.  I disconnect from the server.

**Comment by McJty** [comment] 2016-01-28 16:52
Possibly fixed in 1.2.7

**Closed by McJty** 2016-01-28 16:52 UTC
