### ISSUE TITLE
Client NPE crash

### ISSUE THREAD

**Issue by TechStack** [romelo333/notenoughwands#14] opened 2016-03-04 01:25 UTC
Hey looks like  you get a NPE crash if you use the building wand and look at an entity.
My guess is the MovingObjectPosition is finding the entity instead of the block and passing null to one of your methods :)
Hope this helps
Cheers 

java.lang.NullPointerException: Unexpected error
	at net.minecraft.util.BlockPos.func_177967_a(BlockPos.java:131)
	at net.minecraft.util.BlockPos.func_177972_a(BlockPos.java:126)
	at romelo333.notenoughwands.Items.BuildingWand.findSuitableBlocks(BuildingWand.java:302)
	at romelo333.notenoughwands.Items.BuildingWand.findSuitableBlocks(BuildingWand.java:271)
	at romelo333.notenoughwands.Items.BuildingWand.renderOverlay(BuildingWand.java:259)
	at romelo333.notenoughwands.proxy.ClientProxy.renderWorldLastEvent(ClientProxy.java:45)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_541_ClientProxy_renderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:123)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1407)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1230)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1058)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by McJty** [comment] 2016-03-06 08:14
We will check it out. BTW, what version of Not Enough Wands and what version of MC?

**Comment by TechStack** [comment] 2016-03-06 15:51
It was in a pack i have created its on curse if you want to use it for testing "TSCraft Custom 1.8.9 pack" version 1.16.
It currently uses: 
notenoughwands -1.8.9-1.2.8.jar
forge is 11.15.1.1763

The crash is client side only and will occur when you look at any entity. It was first discovered placing sand that would fall ( falling sand entities ) and later we also had it crash when looking at squid or other players with the wand in hand.

Hope this helps 
Cheers!

**Comment by McJty** [comment] 2016-03-07 07:39
I cannot reproduce this problem. Neither with falling sand, nor with entities like cows. So I'll attempt to do a blind fix based on what I *think* might be wrong. Will be in next version. Reopen this ticket if the upcoming 1.2.9 version does not fix this bug. Thanks

**Closed by McJty** 2016-03-07 07:39 UTC
