### ISSUE TITLE
player corrupted caused

### ISSUE THREAD

**Issue by SDUBZ** [romelo333/notenoughwands#11] opened 2016-02-08 01:44 UTC
player data corruption caused by the protection wand on server

**Comment by McJty** [comment] 2016-02-08 03:57
Can you give more information please? First what version of Minecraft. Secondly why do you think it is caused by the protection wand? What happened exactly?

**Comment by SDUBZ** [comment] 2016-02-08 06:19
it only happends when its in my inventory and when i nbt'ed my palyer.dat and removed i could get back on my server it was when i logged off after crafting it and it was in my inventory when i left the server and then when i came back online later it would let me join and then kick me after 20 seconds and when it wasnt there it would let me join i did many resets of my folder and everything it was exactly the wand of protection and the log didnt help one bit either

**Comment by McJty** [comment] 2016-02-08 06:50
I still need to know what version of Minecraft and Not Enough Wands. And I also need a crashlog

**Comment by SDUBZ** [comment] 2016-02-08 08:42
using forge forge-1.8.9-11.15.1.1734 and not enough wands version notenoughwands-1.8.9-1.2.7

**Comment by SDUBZ** [comment] 2016-02-08 08:43
any more info needed?

**Comment by McJty** [comment] 2016-02-08 08:46
I need logs (both server and client side)

**Comment by SDUBZ** [comment] 2016-02-08 09:17
but the logs didnt report anything

**Comment by SDUBZ** [comment] 2016-02-08 09:22
okay got the logs but where would you like them posted?

**Comment by SDUBZ** [comment] 2016-02-08 09:26
server log http://pastebin.com/0y9StQ68 and client log http://pastebin.com/RFiabNgB both close as possible to conflict happening

**Comment by McJty** [comment] 2016-02-08 09:30
I really need the full logs. I can't do anything with logs that are cut down because there are relevant parts of information at many spots. Can you upload them to bpaste.net? That has a higher limit

**Comment by SDUBZ** [comment] 2016-02-08 09:51
nah thats full reports from me entering and getting kicked from server

**Comment by McJty** [comment] 2016-02-08 09:53
I'm investigating

**Comment by McJty** [comment] 2016-02-08 09:55
There is a lot missing from those logs. Like which mods are in the pack and so on.

**Comment by SDUBZ** [comment] 2016-02-08 10:01
im on modlister mc swh65458 but its down :(

**Comment by McJty** [comment] 2016-02-08 11:28
It is possible that I found the issue. I will later today post an update and then you can see if it is really fixed

**Comment by McJty** [comment] 2016-02-08 11:31
Yes, this will be the issue. Fixed in next release

**Closed by McJty** 2016-02-08 11:31 UTC
